name: New Detection Rule
description: Suggest a new security detection rule
title: '[Rule]: '
labels: ['new-rule']
body:
  - type: markdown
    attributes:
      value: |
        Suggest a new detection rule for Extension Guard.

  - type: input
    id: name
    attributes:
      label: Rule Name
      placeholder: 'Suspicious File Access'
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Suggested Severity
      options:
        - Critical
        - High
        - Medium
        - Low
        - Info
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What should this rule detect?
      description: Describe the malicious behavior or pattern
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: Example code patterns that should be detected
      render: javascript

  - type: input
    id: mitre
    attributes:
      label: MITRE ATT&CK Technique
      description: If applicable, the MITRE technique ID
      placeholder: 'T1005'

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to related security research or CVEs
