import type { Reporter, ReporterOptions } from './reporter.interface.js';
import type { FullScanReport, ScanResult, Finding, Severity } from '../types/index.js';

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🟢',
  info: '⚪',
};

const RISK_EMOJI: Record<string, string> = {
  critical: '⛔',
  high: '🔴',
  medium: '🟡',
  low: '🟢',
  safe: '✅',
};

export class MarkdownReporter implements Reporter {
  readonly format = 'markdown';

  generate(report: FullScanReport, options: ReporterOptions = {}): string {
    const { includeSafe = false } = options;
    const lines: string[] = [];

    lines.push('# Extension Guard Scan Report');
    lines.push('');
    lines.push(`**Scan ID:** \`${report.scanId}\``);
    lines.push(`**Date:** ${new Date(report.timestamp).toLocaleString()}`);
    lines.push(`**Extension Guard Version:** ${report.version}`);
    lines.push('');

    // Environment
    lines.push('## Environment');
    lines.push('');
    lines.push(`- **OS:** ${report.environment.os}`);
    for (const ide of report.environment.ides) {
      lines.push(`- **${ide.name}:** ${ide.path} (${ide.extensionCount} extensions)`);
    }
    lines.push('');

    // Summary
    lines.push('## Summary');
    lines.push('');
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Total Extensions | ${report.totalExtensions} |`);
    lines.push(`| Unique Extensions | ${report.uniqueExtensions} |`);
    lines.push(`| Health Score | ${report.summary.overallHealthScore}% |`);
    lines.push(`| Scan Duration | ${(report.scanDurationMs / 1000).toFixed(2)}s |`);
    lines.push('');

    // Risk Level Breakdown
    lines.push('### Risk Level Distribution');
    lines.push('');
    lines.push('| Risk Level | Count |');
    lines.push('|------------|-------|');
    for (const [level, count] of Object.entries(report.summary.byRiskLevel)) {
      if (count > 0 || includeSafe) {
        lines.push(`| ${RISK_EMOJI[level] || ''} ${level} | ${count} |`);
      }
    }
    lines.push('');

    // Severity Breakdown
    const totalFindings = Object.values(report.summary.bySeverity).reduce((a, b) => a + b, 0);
    if (totalFindings > 0) {
      lines.push('### Findings by Severity');
      lines.push('');
      lines.push('| Severity | Count |');
      lines.push('|----------|-------|');
      for (const [severity, count] of Object.entries(report.summary.bySeverity)) {
        if (count > 0) {
          lines.push(`| ${SEVERITY_EMOJI[severity as Severity] || ''} ${severity} | ${count} |`);
        }
      }
      lines.push('');
    }

    // Critical and High Risk Extensions
    const riskyResults = report.results.filter(
      (r) => r.riskLevel === 'critical' || r.riskLevel === 'high'
    );

    if (riskyResults.length > 0) {
      lines.push('## ⚠️ High Risk Extensions');
      lines.push('');
      for (const result of riskyResults) {
        lines.push(...this.formatExtensionResult(result));
      }
    }

    // Medium Risk Extensions
    const mediumResults = report.results.filter((r) => r.riskLevel === 'medium');
    if (mediumResults.length > 0) {
      lines.push('## Medium Risk Extensions');
      lines.push('');
      for (const result of mediumResults) {
        lines.push(...this.formatExtensionResult(result));
      }
    }

    // Safe Extensions (if requested)
    if (includeSafe) {
      const safeResults = report.results.filter(
        (r) => r.riskLevel === 'safe' || r.riskLevel === 'low'
      );
      if (safeResults.length > 0) {
        lines.push('## ✅ Safe Extensions');
        lines.push('');
        lines.push('| Extension | Version | Trust Score |');
        lines.push('|-----------|---------|-------------|');
        for (const result of safeResults) {
          lines.push(`| ${result.extensionId} | ${result.version} | ${result.trustScore}/100 |`);
        }
        lines.push('');
      }
    }

    // Footer
    lines.push('---');
    lines.push('');
    lines.push('*Generated by [Extension Guard](https://github.com/aspect-guard/extension-guard)*');

    return lines.join('\n');
  }

  private formatExtensionResult(result: ScanResult): string[] {
    const lines: string[] = [];

    lines.push(`### ${RISK_EMOJI[result.riskLevel] || ''} ${result.extensionId}`);
    lines.push('');
    lines.push(`- **Display Name:** ${result.displayName}`);
    lines.push(`- **Version:** ${result.version}`);
    lines.push(`- **Publisher:** ${result.metadata.publisher.name}`);
    lines.push(`- **Trust Score:** ${result.trustScore}/100`);
    lines.push(`- **Risk Level:** ${result.riskLevel}`);
    lines.push('');

    if (result.findings.length > 0) {
      lines.push('#### Findings');
      lines.push('');
      for (const finding of result.findings) {
        lines.push(...this.formatFinding(finding));
      }
    }

    return lines;
  }

  private formatFinding(finding: Finding): string[] {
    const lines: string[] = [];
    const emoji = SEVERITY_EMOJI[finding.severity] || '';

    lines.push(`- ${emoji} **${finding.severity.toUpperCase()}:** ${finding.title}`);
    lines.push(`  - ${finding.description}`);
    if (finding.evidence.filePath) {
      const location = finding.evidence.lineNumber
        ? `${finding.evidence.filePath}:${finding.evidence.lineNumber}`
        : finding.evidence.filePath;
      lines.push(`  - 📍 Location: \`${location}\``);
    }
    if (finding.mitreAttackId) {
      lines.push(`  - 🎯 MITRE ATT&CK: ${finding.mitreAttackId}`);
    }
    lines.push('');

    return lines;
  }
}
